import Navbar from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'imamrifai.dev',
  description: 'Generated by create next apLover of JavaScript, coding enthusiast, constantly learning and growing, building amazing projects.',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" id='home'>
      <body className={inter.className}>
      {children}</body>
    </html>
  )
}
