'use client'
import { useState } from 'react'
import './globals.css'
import Navbar from './components/Navbar'

export const metadata = {
  title: 'imamrifai.dev',
  description: 'Generated by create next apLover of JavaScript, coding enthusiast, constantly learning and growing, building amazing projects.',
}

export default function RootLayout({ children }) {

  const [isDark , setIsDark] = useState(false)

  const handleDarkMode = () => {
    document.body.classList.toggle('dark')
    setIsDark(!isDark)
  }

  return (
    <html lang="en" id='home'>
      <body className="duration-300 transition-all">
      <Navbar isDark={isDark} handleDarkMode={handleDarkMode}/>
      {children}</body>
    </html>
  )
}
