import './globals.css'
import { Poppins } from 'next/font/google'

export const metadata = {
  title: 'imamrifai.dev',
  description: 'Generated by create next apLover of JavaScript, coding enthusiast, constantly learning and growing, building amazing projects.',
}

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

export default function RootLayout({ children }) {

  

  return (
    <html lang="en">
      <body className={poppins.className}>
      {/* <Navbar /> */}
      {children}</body>
    </html>
  )
}
